
service: avaliacao-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::703846776328:role/LabRole
  environment:
    sqs_url: !Sub https://sqs.us-east-1.amazonaws.com/703846776328/trab-final-serverless

functions:
  sqsHandler:
    handler: handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:703846776328:trab-final-serverless
          batchsize: 1
          enabled: true
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:703846776328:table/shopping-list/stream/2023-03-13T02:39:04.196
          batchSize: 1
          maximumRetryAttempts: 10
          enabled: true